### ISSUE TITLE
Qt: Qt6 Roadmap

### ISSUE THREAD

**Issue by JanNowak94** [smplayer-dev/smplayer#632]
As last version of KDE 5 starts to be worked on - smplayer still does not have port that uses Qt6 - we need to fix that. Unless it does want to end as other qt4 projects that didn't ported to qt5 back the day.

**some** Identified issues:
- [ ] not defined:
- - [x] QMenu in actionseditor.cpp
- [ ] duplicates:
- - [x] 'class QStringList;' (already included) in: 
- - - [x] mplayerprocess.h
- - - [x] mpvprocess.h
- [ ] removed functions
- - [ ] ahortcutgetter.cpp:
- - - [ ] QVBoxLayout::setMargin ShortcutGetter::ShortcutGetter(QWidget *parent) : QDialog(parent) line 270
- - [ ] actionseditor.cpp
- - - [ ] QVBoxLayout::setMargin ActionsEditor::ActionsEditor(QWidget*, Qt::WindowFlags) line 227
- - - [ ] QTextStream::setCodec ActionsEditor::saveActionsTable(const QString&) line 538
- - - [ ] QTextStream::setCodec ActionsEditor::loadActionsTable(const QString&) line 579
- [x] use QT_VERSION for include QDesktopWidget in desktopinfo.cpp
- [ ] remove RegExp from:
- - [ ] paths.cpp:
- - - [ ] Paths::doc
- - [ ] helper.cpp:
- - - [ ] Helper::qtVersion
- - - [ ] Helper::searchForConsecutiveFiles
- - - [ ] Helper::directoryContainsDVD
- - [ ] colorutils.cpp:
- - - [ ] ColorUtils::AARRGGBBToColor
- - [ ] actionseditor.cpp:
- - - [ ] ActionsEditor::loadActionsTable(const QString &)
- [ ] ...

Required for MPV_AUDIO_DEVICES
- [ ] Remove RegExp from:
- - [ ] deviceinfo.cpp:
- - - [ ] DeviceList DeviceInfo::mpvAudioDevices(const QString &, const QString &)
- [ ] ...

Required for USE_XV_ADAPTORS
- [ ] remove RegExp from:
- - [ ] deviceinfo.cpp:
- - - [ ] DeviceInfo::xvAdaptors
- [ ] ...

Required for USE_PULSEAUDIO_DEVICES
- [ ] remove RegExp from:
- - [ ] deviceinfo.cpp:
- - - [ ] DeviceInfo::paDevices
- [ ] ...

Required for COLOR_OUTPUT_SUPPORT:
- [ ] Remove RegExp feom:
- - [ ] colorutils.cpp:
- - - [ ] ColorUtils::stripColorsTags 
- [ ] ...

Identified compatibility issues (need qt5compat - should be ported but not essential now)
- [ ] use of QTextCodec is in qt5compat - note that setCodec is not a function even with qt5compat.
- [ ] ...

**Comment by JanNowak94** [comment]
desktopinfo.cpp fix:
`//change 21 line:
#include <QDesktopWidget>
//to
#if QT_VERSION < 0x060000
#include <QDesktopWidget>
#else
#include <QWidget>
#endif

**Comment by maverick74** [comment]
Nothing new on this front?

**Comment by n3thshan** [comment]
hi is this updated or abandoned?

**Comment by NikitaBeloglazov** [comment]
Bump
Any progress?:(

**Comment by smplayer-dev** [comment]
No.

**Comment by Raza-0007** [comment]
Hello Ricardo,

Qt 5 support [ended on May 26 2025](https://www.qt.io/blog/extended-security-maintenance-for-qt-5.15-begins-may-2025). Do you have any plans to upgrade smplayer to Qt 6? 

I do not know how hard it will be or how much work will be required, but please consider upgrading sooner rather than later because as time goes on, smplayer complied on Qt 5 will start becoming a security risk, especially because smplayer can access internet to stream videos.

Thanks in advance,

**Comment by smplayer-dev** [comment]
Yes, don't worry, it will be done. It’s just a bit tedious and time-consuming.

**Comment by a17r** [comment]
### Qt5 is now declared deprecated in Gentoo

The final release happened on 2025-05-19, which means a) we will not get it until 2026-06-19, b) any bugs discovered since last May will not be fixed and c) no bugs since 2020-12-08 that haven't also been affecting Qt6 were fixed at all.

**Comment by Raza-0007** [comment]
A user @Sportacandy has submitted a [pull request for a patch](https://github.com/smplayer-dev/smplayer/pull/1224) that allows smplayer to be build with Qt6. He says it is working fine. I hope @smplayer-dev can find some free time to review this patch and if everything is fine, merge it in the repo and provide us a with a Qt6 version of smplayer alongside the Qt5 ones.

**Comment by smplayer-dev** [comment]
I created a branch with the Qt6 code:
https://github.com/smplayer-dev/smplayer/tree/qt6

**Comment by Raza-0007** [comment]
That is great! When you get a chance can you please build a Qt 6 based portable Windows version for testing?

**Comment by smplayer-dev** [comment]
https://github.com/smplayer-dev/smplayer/actions/runs/17513441959/artifacts/3943587493

**Comment by Raza-0007** [comment]
Thank you. It is working great! I have updated the included mpv to version 0.40 (Aug 18 2025 release), and so far so good. I am going to test it for the next few days, and if I encounter an issue, I will report back.

And thank you for building with the Qt 6.8 branch!

**Comment by maverick74** [comment]
@smplayer-dev Is there any ETA for a stable release compatible with Qt6 (or even better Qt6-only)?

Would be great to have smplayer _refreshed_

**Comment by smplayer-dev** [comment]
There are a lot of changes to support Qt 6, so it’ll take some time to test and make sure nothing’s broken.

**Comment by Raza-0007** [comment]
I have been using the portable version of Qt 6.8 for Windows extensively for the last three days and it has been working flawlessly with zero issues. I ported over my smplayer config from the Qt 5.15 version; where I have a customized GUI, a custom mpv config and customized keyboard shortcuts. I have used all the basic options and buttons one needs in video and music playback and everything is working without a glitch. 

There were two minor issues but one was introduced after updating the mpv inside, and the other already existed in Qt 5.15, so they are not a result of Qt 6.8 port, and can be dealt with later on.

As far as I am concerned, the Qt 6.8 version of smplayer is ready to go for the Windows OS at least.

**Comment by maverick74** [comment]
@Raza-0007 still all good with Qt6 version?

**Comment by Raza-0007** [comment]
@maverick74, actually no. When I initially checked it, it was just with regular English shows and music, where there is only one audio track and I do not need subtitles. Later when I played Japanese anime on it which had multiple audio tracks and multiple subtitle tracks, I found the issue. The QT 6.8 version does not detect additional audio tracks or subtitle tracks. They don't show up in selection. It just plays the default audio track. 

I was also having difficulty generating logs from the menu -> view -> mpv log/smplayer log.

So I removed it and moved back to the Qt 5.15 version. But nowadays I only use smplayer as a backup music player. I use native mpv with uosc and thumbfast integrated as my main media player.

**Comment by maverick74** [comment]
Thanks for sharing your experience! I was hopping for a Qt6 sooner rather than later... now I guess it will be later...

**Comment by smplayer-dev** [comment]
I can't reproduce this problem.
<img width="325" height="203" alt="Image" src="https://github.com/user-attachments/assets/1a2c8d48-6269-4474-afaf-3cc76e4ba863" />

**Comment by sergiomb2** [comment]
is to test branch qt6 ? I see some updates there

**Comment by Raza-0007** [comment]
> I can't reproduce this problem.

@smplayer-dev, thanks for checking on this issue. Just to clarify, this is from the Qt 6.8 branch portable smplayer that you [compiled on Sept 6, 2025](https://github.com/smplayer-dev/smplayer/issues/632#issuecomment-3262126351) above, the link is now expired. 

Here is the smplayer log and the corresponding mpv log for an anime file with dual audio and dual subtitle tracks, where smplayer failed to load the audio tracks and subtitle tracks.

[smplayer_log.txt](https://github.com/user-attachments/files/24547285/smplayer_log.txt)

[mpv_log.txt](https://github.com/user-attachments/files/24547286/mpv_log.txt)

Strangely, the tracks randomly show up if you relaunch the player and play the same file again, and then they disappear again on some next random relaunch. I did not notice this before. 

Also, I had to write the logs to file from inside preferences. Before when I tried to generate a log from "view -> smplayer log", with the video paused, smplayer crashed!

Hopefully you can pinpoint the bug from the logs.

**Comment by smplayer-dev** [comment]
> > I can't reproduce this problem.
> 
> [@smplayer-dev](https://github.com/smplayer-dev), thanks for checking on this issue. Just to clarify, this is from the Qt 6.8 branch portable smplayer that you [compiled on Sept 6, 2025](https://github.com/smplayer-dev/smplayer/issues/632#issuecomment-3262126351) above, the link is now expired.
> 
That's the same version I used to test. Maybe it's because you're using a newer version of mpv, but I have also tested with mpv v0.40.0-90-g3600c716e (on Linux) and it works ok.

**Comment by Raza-0007** [comment]
@smplayer-dev, then it is most likely the custom config that I include in smplayer for mpv. But I am surprised that it could be causing this issue as it is nothing special just `profile=high-quality`, `dither-depth=auto`, `deinterlace=auto`, `deband=yes`, `hwdec=auto`, `video-sync=display-resample` 

I tested it with the default config and was also unable to reproduce the dual tracks issue, but the logs issue is present in the default build as smplayer again crashed while generating a smplayer log while the video was playing.

I remember that I ported over my config from the Qt 5.15 branch, maybe that is causing this issue with Qt 6.8 branch. Give me some time and I will try to narrow what in my config is causing this issue with smplayer.

**Comment by Raza-0007** [comment]
@smplayer-dev,

An update on the multiple audio tracks and subtitles issue with the Qt 6.8 smplayer. 

This time instead of importing my config from Qt 5.15 player, I decided to start over in Qt 6.8 player from scratch. First I reset the player to default by deleting the config folder. Tested it and everything was working fine. 

Then:

Step 1: Upgraded mpv inside to the Jan 10, 2026 build (mpv v0.41.0-66-g9483d6e12). Everything was good.

Step 2: Added my custom mpv config. Everything was still good.

Step 3: Imported my keybinding from Qt 5.15 branch. Everything was still testing good.

So we can rule out any of the above as the cause of the issue.
 
Unfortunately, while I was sorting out the toolbars and the cosmetic look and feel of the player, the issue somehow got triggered and once it got triggered, then it started happening on every other relaunch of the player. I had to reset the config back to default to get rid of the issue again. I am still not sure what actually triggered it, but the issue is present and it does not happen with the Qt 5.15 player. 

I recommend releasing a beta build of Qt 6.8 smplayer for everyone to test, so if there are some issues like this, others will encounter them and hopefully report back.

**Comment by maverick74** [comment]
Is there any Qt6 beta version out "somewhere" that I'm not aware of?

**Comment by smplayer-dev** [comment]
You can find here a version for Windows with Qt 6 (smplayer-portable-25.6.0.10411-x64-qt6.7z)
https://github.com/smplayer-dev/smplayer/releases/tag/v10403

**Comment by arokettu** [comment]
this is still important but unresolved (comment for the bot)

**Comment by Sportacandy** [comment]
I thought that the Qt6 migration is most natural way for the project, but the maintainers don't seem to think so.
Staying Qt5 is far from my needs, so I decided to start a new project and I won't be back here. Farewells all.

**Comment by maverick74** [comment]
> I thought that the Qt6 migration is most natural way for the project, but the maintainers don't seem to think so.

Not sure what you mean!!! Qt6 is well underway! You even have test versions of it!!! 

Also, while I understand it's very boring to wait, lets not all forget the tremendous effort most OpenSource devs do, working on this and other projects on their free time, almost always for free!!!

I get it we all want a Qt6 version (yeah! Me too!)!!! But that's not a small feat!!! It's not a small and quick bug fix or a little detail!!! It's heavy code!!! And heavy code while also dealing with small and quick bug fixes that impact many people!!!

Lets remember their effort and, if we can, also help them 🙂! It's for all of us! 🙂

**Comment by smplayer-dev** [comment]
There's a branch containing the Qt 6 code:
https://github.com/smplayer-dev/smplayer/tree/qt6

I don't want to make the Qt 6 version the default yet, as it hasn't been tested extensively.

**Comment by Polynomial-C** [comment]
> There's a branch containing the Qt 6 code: https://github.com/smplayer-dev/smplayer/tree/qt6
> 
> I don't want to make the Qt 6 version the default yet, as it hasn't been tested extensively.

So to give you some (hopefully useful) feedback on that… I am using the qt6 branch since around October 2025 on Linux with no issues. Most of the time you roll a (pre-)release I do the same for qt6 branch and build that on my Linux systems. Works like a charm.

**Comment by a17r** [comment]
> ### Qt5 is now declared deprecated in Gentoo
> The final release happened on 2025-05-19, which means a) we will not get it until 2026-06-19, b) any bugs discovered since last May will not be fixed and c) no bugs since 2020-12-08 that haven't also been affecting Qt6 were fixed at all.

I may have understated the urgency back then. Please note that the final remaining Qt5 packages were treecleaned from the official Gentoo repository back in June 2026, after having been "masked" (not available for use without manual intervention) since February.

smplayer only remains available in Gentoo because someone cared enough to package a snapshot from the cited Qt6 development branch, which is not something we [or other distributions similarly seeking to remove Qt5] usually do. This has not resulted in additional bugs filed for that snapshot since **November 2025**, fwiw.

**Comment by sergiomb2** [comment]
I build SMPlayer for Fedora with Qt6 (the `qt6` branch) on COPR:

https://copr.fedorainfracloud.org/coprs/sergiomb/mpv/

Everything I tested worked well.

**Comment by arokettu** [comment]
@sergiomb2 
Playing from the SMB share does not work, changing `smplayer %U` to `smplayer %F` fixes that

**Comment by arokettu** [comment]
Also icons in the interface look blurry (KDE, Wayland, 175%)
Just reporting. It's minor enough for me not to care

**Comment by sergiomb2** [comment]
Ah, I dropped this old patch: https://src.fedoraproject.org/rpms/smplayer/blob/rawhide/f/smplayer-21.08.0-desktop-files.patch, but it seems to still be needed. Maybe the project should accept this change, as apparently it’s not only the old Nautilus that needs %F or %f.

**Comment by yolanjoy** [comment]
The latest QT6 version does not have the fix for this issue - https://github.com/smplayer-dev/smplayer/issues/1404

**Comment by sergiomb2** [comment]
> The latest QT6 version does not have the fix for this issue - [#1404](https://github.com/smplayer-dev/smplayer/issues/1404)

I just built 26.8.29-2.qt6 in my COPR repo, which includes the fix you mentioned. This may be the proper fix for the problem mentioned here: https://github.com/smplayer-dev/smplayer/issues/632#issuecomment-5655040975

For those who already have smplayer-26.8.29-2.qt6 installed, just run `dnf update` 😃

**Comment by arokettu** [comment]
@sergiomb2 I confirm, works with %U now

**Comment by VVD** [comment]
How to build from qt6 branch?
```
Project ERROR: Unknown module(s) in QT: script
*** Error code 3
```

**Comment by smplayer-dev** [comment]
You need these packages (ubuntu):

libqt6core5compat6-dev
libqt6opengl6-dev
qt6-base-dev
qt6-base-dev-tools
qt6-base-private-dev
qt6-declarative-dev
qt6-declarative-dev-tools
qt6-tools-dev
qt6-tools-dev-tools

**Comment by VVD** [comment]
I have installed:
qt6-5compat-6.11.2
qt6-base-6.11.2
qt6-base_sqldriver-sqlite-6.11.2
qt6-charts-6.11.2
qt6-connectivity-6.11.2
qt6-declarative-6.11.2
qt6-imageformats-6.11.2
qt6-languageserver-6.11.2
qt6-location-6.11.2
qt6-multimedia-6.11.2_1
qt6-networkauth-6.11.2
qt6-pdf-6.11.2
qt6-positioning-6.11.2
qt6-quick3d-6.11.2
qt6-quicktimeline-6.11.2
qt6-remoteobjects-6.11.2
qt6-scxml-6.11.2
qt6-sensors-6.11.2
qt6-serialport-6.11.2
qt6-shadertools-6.11.2
qt6-speech-6.11.2
qt6-svg-6.11.2
qt6-tools-6.11.2
qt6-translations-6.11.2
qt6-wayland-6.11.2
qt6-webchannel-6.11.2
qt6-webengine-6.11.2
qt6-websockets-6.11.2
qt6-webview-6.11.2

What command run to build?
qmake6 and then gmake in src dir? Something else?

P.S. I'm the maintainer of port multimedia/smplayer in FreeBSD:
https://cgit.freebsd.org/ports/tree/multimedia/smplayer
https://www.freshports.org/multimedia/smplayer/

**Comment by sergiomb2** [comment]
You build it the same way you did before. There are no changes from the previous builds.

**Comment by VVD** [comment]
As I wrote before:
```
Project ERROR: Unknown module(s) in QT: script
*** Error code 3
```

**Comment by smplayer-dev** [comment]
In ubuntu:
```
./get_version.sh 
cd src/
qmake6
make -j4
```
